<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Event\EventInterface;

/**
 * Solicitacoes Controller
 *
 * @property \App\Model\Table\SolicitacoesTable $Solicitacoes
 * @method \App\Model\Entity\Solicitaco[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class SolicitacoesController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['add','view','transferir','minhasturmas']);
    }

    public function isAuthorized($user)
    {
        if ($user['categoria'] == 'SUPREMO') {
            return true;
        } else {
            if (in_array($user['categoria'], ['COORDENADOR'])) {
                if (in_array($this->request->getParam('action'), ['index','pendentes','abertas','abrir','fechar'])) {
                    return true;
                }
            } else {
                if (in_array($this->request->getParam('action'), ['index'])){
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $user = $this->Auth->user();
        $user['professor'] = $this->getTableLocator()->get('Professores')->find()->where(['users_id'=>$user['id']])->first();
        $curso = $this->getTableLocator()->get('Cursos')->find()->where(['Cursos.professores_id'=>$user['professor']->id])->first();

        $sol = $this->Solicitacoes->find()->contain(['Diarios.Turmas.Cursos','Diarios.Professores']);
        $solicitacoes = array();
        foreach ($sol as $sol){
            if($sol->diario->turma->curso->id == $curso->id){
                $solicitacoes[] = $sol;
            }
        }

        $this->set(compact('solicitacoes','user'));
    }

    public function pendentes()
    {
        $user = $this->Auth->user();
        $user['professor'] = $this->getTableLocator()->get('Professores')->find()->where(['users_id'=>$user['id']])->first();
        $curso = $this->getTableLocator()->get('Cursos')->find()->where(['Cursos.professores_id'=>$user['professor']->id])->first();

        $solicitacoes = $this->Solicitacoes->find()->contain(['Diarios.Turmas.Cursos','Diarios.Professores'])->where(['Solicitacoes.status'=>0])->order(['data']);
        $pendentes = [];
        foreach ($solicitacoes as $solicitacao){
            if($solicitacao->diario->turma->curso->id == $curso->id){
                $pendentes[] = $solicitacao;
            }
        }
        $this->set(compact('pendentes','user'));
    }

    public function abertas()
    {
        $user = $this->Auth->user();
        $user['professor'] = $this->getTableLocator()->get('Professores')->find()->where(['users_id'=>$user['id']])->first();
        $curso = $this->getTableLocator()->get('Cursos')->find()->where(['Cursos.professores_id'=>$user['professor']->id])->first();

        $solicitacoes = $this->Solicitacoes->find()->contain(['Diarios.Turmas.Cursos','Diarios.Professores'])->where(['Solicitacoes.status'=>1])->order(['data']);
        $pendentes = [];
        foreach ($solicitacoes as $solicitacao){
            if($solicitacao->diario->turma->curso->id == $curso->id){
                $pendentes[] = $solicitacao;
            }
        }
        $this->set(compact('pendentes','user'));
    }


    public function abrir($id){
        $solicitacao = $this->Solicitacoes->get($id);
        $solicitacao->status = 1;
        if($this->Solicitacoes->save($solicitacao)){
            $this->Flash->success('Solicitação deferido com sucesso');
            //$this->msg_abrir($permuta);
            $this->redirect(['controller'=>'principal','action'=>'index']);
        }
    }

    public function fechar($id){
        $solicitacao = $this->Solicitacoes->get($id);
        $solicitacao->status = 2;
        if($this->Solicitacoes->save($solicitacao)){
            $this->Flash->success('Solicitação finalizada com sucesso');
            $this->redirect(['controller'=>'principal','action'=>'index']);
        }
    }

    /**
     * View method
     *
     * @param string|null $id Solicitaco id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view()
    {
        $this->viewBuilder()->setLayout('home');
        if($this->request->is('post')){
            $dados = $this->request->getData();
            $docente = $this->getTableLocator()->get('Professores')
                ->find()
                ->where(['Professores.siape'=>$dados['siape']])
                ->first();

            $diarios = $this->getTableLocator()->get('Diarios')
                ->find()
                ->contain(['Professores','Turmas.Cursos'])
                ->where(['Professores.siape'=>$dados['siape']])
                ->all();
            if($diarios->count() == 0){
                $this->Flash->error('Não foram encontrados diários para o SIAPE '.$dados['siape'].'.');
            }else{
                $this->set(compact('diarios'));
                $this->set(compact('docente'));
            }
        }//Fim do IF do Post
    }

    public function transferir($id)
    {
        $this->viewBuilder()->setLayout('home');


        $solicitacao = $this->Solicitacoes->newEmptyEntity();

        if($this->request->is('post')){

            $solicitaco = $this->Solicitacoes->patchEntity($solicitacao, $this->request->getData());
            $dados = $this->request->getData();

            //$diario = $this->getTableLocator()->get('Turma')->get($id);
            //$solicitacao->diario = $diario;

            $existe = false;

            if(isset($dados['primeiro'])){
                $solicitacao->horarios = $solicitacao->horarios . '1º  ';
                $existe = true;
            }
            if(isset($dados['segundo'])){
                $solicitacao->horarios = $solicitacao->horarios . '2º  ';
                $existe = true;
            }
            if(isset($dados['terceiro'])){
                $solicitacao->horarios = $solicitacao->horarios . '3º  ';
                $existe = true;
            }
            if(isset($dados['quarto'])){
                $solicitacao->horarios = $solicitacao->horarios . '4º  ';
                $existe = true;
            }
            if(isset($dados['quinto'])){
                $solicitacao->horarios = $solicitacao->horarios . '5º  ';
                $existe = true;
            }
            if(isset($dados['sexto'])){
                $solicitacao->horarios = $solicitacao->horarios . '6º  ';
                $existe = true;
            }

            //Pegando o dia da semana
            $diasemana = array('Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sabado');
            $diasemana_numero = date('w', strtotime($dados['data']));
            $solicitacao->dia =  $diasemana[$diasemana_numero];

            $solicitacao->status = 0;
            $solicitacao->registro = 0;

            if(!$existe){
                $this->Flash->error(__('Selecione os dias!'));
            }elseif ($this->Solicitacoes->save($solicitacao)) {

                //$this->mensagem($solicitacao);
                //$this->lembrete_coordenador($solicitacao);
                $this->Flash->success(__('Solicitação realizada com sucesso!.'));
                if($this->Auth->user()== null){
                    return $this->redirect(['controller'=>'solicitacoes','action' => 'view']);
                }
                return $this->redirect(['controller'=>'solititacoes','action' => 'view']);
            }
            $this->Flash->error(__('Erro ao tentar solicitar a permuta.'));

        }//Fim da requisição do post

        $user = $this->Auth->user();
        $turma = $this->getTableLocator()->get('Turmas')->get($id,['contain'=>'Cursos']);
        $diarios = $this->getTableLocator()->get('Diarios')->find()->where(['turmas_id'=>$id])->contain(['Professores','Turmas.Cursos'])->find('list')->all();
        $diarios_dados = $this->getTableLocator()->get('Diarios')->find()->where(['turmas_id'=>$id])->contain(['Professores','Turmas.Cursos'])->all()->toList();

        $this->set(compact('user','solicitacao','diarios','diarios_dados','turma'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add($id)
    {
        $this->viewBuilder()->setLayout('home');
        //$user = $this->Auth->user();
        //$user['professor'] = $this->getTableLocator()->get('Professores')->find()->where(['users_id'=>$user['id']])->first();


        $user = $this->Auth->user();
        $diario = $this->getTableLocator()->get('Diarios')->get($id,['contain'=>['Professores', 'Turmas.Cursos']]);
        //$professores = $this->getTableLocator()->get('Professores')->find()->all();


        $solicitacao = $this->Solicitacoes->newEmptyEntity();

        if ($this->request->is('post')) {
            $solicitaco = $this->Solicitacoes->patchEntity($solicitacao, $this->request->getData());
            $dados = $this->request->getData();

            $solicitaco->diario = $diario;

            //$solicitacao->diario = $diario;
            $existe = false;

            if(isset($dados['primeiro'])){
                $solicitacao->horarios = $solicitacao->horarios . '1º  ';
                $existe = true;
            }
            if(isset($dados['segundo'])){
                $solicitacao->horarios = $solicitacao->horarios . '2º  ';
                $existe = true;
            }
            if(isset($dados['terceiro'])){
                $solicitacao->horarios = $solicitacao->horarios . '3º  ';
                $existe = true;
            }
            if(isset($dados['quarto'])){
                $solicitacao->horarios = $solicitacao->horarios . '4º  ';
                $existe = true;
            }
            if(isset($dados['quinto'])){
                $solicitacao->horarios = $solicitacao->horarios . '5º  ';
                $existe = true;
            }
            if(isset($dados['sexto'])){
                $solicitacao->horarios = $solicitacao->horarios . '6º  ';
                $existe = true;
            }

            //Pegando o dia da semana
            $diasemana = array('Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sabado');
            $diasemana_numero = date('w', strtotime($dados['data']));
            $solicitacao->dia =  $diasemana[$diasemana_numero];

            $solicitacao->status = 0;
//            if($solicitaco->tipo == 'Permuta'){
//                $solicitacao->retorno = 'Não';
//            }else{
//                $solicitacao->retorno = 'NA';
//            }
            $solicitacao->registro = 0;

            if(!$existe){
                $this->Flash->error(__('Selecione os dias!'));
            }elseif ($this->Solicitacoes->save($solicitacao)) {

                //$this->mensagem($solicitacao);
                //$this->lembrete_coordenador($solicitacao);
                $this->Flash->success(__('Solicitação realizada com sucesso!.'));
                if($this->Auth->user()== null){
                    return $this->redirect(['controller'=>'solicitacoes','action' => 'view']);
                }
                return $this->redirect(['controller'=>'solicitacoes','action' => 'view']);
            }
            $this->Flash->error(__('Erro ao tentar solicitar a permuta.'));
        }

        $this->set(compact('solicitacao'));
        $this->set(compact('diario'));
        $this->set(compact( 'user'));
        //$this->set(compact('professores'));

    }

    /**
     * Edit method
     *
     * @param string|null $id Solicitaco id.
     * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $solicitaco = $this->Solicitacoes->get($id, [
            'contain' => [],
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $solicitaco = $this->Solicitacoes->patchEntity($solicitaco, $this->request->getData());
            if ($this->Solicitacoes->save($solicitaco)) {
                $this->Flash->success(__('The solicitaco has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The solicitaco could not be saved. Please, try again.'));
        }
        $diarios = $this->Solicitacoes->Diarios->find('list', ['limit' => 200])->all();
        $this->set(compact('solicitaco', 'diarios'));
    }



    /**
     * Delete method
     *
     * @param string|null $id Solicitaco id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $solicitaco = $this->Solicitacoes->get($id);
        if ($this->Solicitacoes->delete($solicitaco)) {
            $this->Flash->success(__('The solicitaco has been deleted.'));
        } else {
            $this->Flash->error(__('The solicitaco could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
